package gui;
import javafx.application.Application;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.scene.Scene;
import javafx.scene.control.*;
import javafx.scene.layout.*;
import javafx.stage.Stage;
import javafx.scene.text.*;
import javafx.geometry.*;
import javafx.collections.*;
//import java.util.List;
//import java.util.ArrayList;
//import domain.Storage;
//import domain.DBStorage;
//import domain.Employee;
//import domain.Truck;
//import java.awt.Desktop;
//import java.net.*;
public class MainWindow extends Application{
  private TextField searchField;
  private Button searchButton;
  private Button clearResultButton;
  private Button submitButton;
  private Menu editMenu;
  private Menu fileMenu;
  private MenuItem showEmployee;
  private MenuItem showTruck;
  private MenuItem addEmployee;
  private MenuItem deleteEmplyee;
  private MenuItem addTruck;
  private MenuItem deleteTruck;
  private MenuItem exitApplication;
  private Button logginButton;
  private Button loggoutButton;
  private BorderPane mainPane;
  private GridPane pane1;
  private GridPane pane2;
  private GridPane pane3;
  private VBox pane4;
  public static void main(String[] args){

    launch(args);
  }
  public void start(Stage primaryStage) throws Exception{
  primaryStage.setTitle("HarborMaster");
  mainPane = new BorderPane();
  pane1 = new GridPane();
  pane2 = new GridPane();
  pane4 = new VBox(20);
  pane3 = new GridPane();
  logginButton = new Button("Sign in");
  loggoutButton = new Button("Sign out");
  pane2.setPadding(new Insets(10,10,10,10));
  pane2.setVgap(8);
  pane2.setHgap(10);
  pane2.setConstraints(logginButton,0,0);
  pane2.setConstraints(loggoutButton,0,1);
  pane2.getChildren().addAll(logginButton,loggoutButton);
  mainPane.setRight(pane2);
  fileMenu = new Menu("File");
  showEmployee = new MenuItem("Show Employee");
  showTruck = new MenuItem("Show Truck");
  exitApplication = new MenuItem("Exit");
  fileMenu.getItems().add(showEmployee);
  fileMenu.getItems().add(showTruck);
  fileMenu.getItems().add(new SeparatorMenuItem());
  fileMenu.getItems().add(exitApplication);
  editMenu = new Menu("Edit");
  addEmployee = new MenuItem("Add new Employee...");
  deleteEmplyee = new MenuItem("Delete Employee...");
  addTruck = new MenuItem("Add new Truck...");
  deleteTruck = new MenuItem("Delete Truck");
  editMenu.getItems().add(addEmployee);
  editMenu.getItems().add(deleteEmplyee);
  editMenu.getItems().add(new SeparatorMenuItem());
  editMenu.getItems().add(addTruck);
  editMenu.getItems().add(deleteTruck);
  MenuBar menubar = new MenuBar();
  menubar.getMenus().addAll(fileMenu);
  menubar.getMenus().addAll(editMenu);
  mainPane.setTop(menubar);
  clearResultButton = new Button("Clear result");
  pane1.setVgap(10);
  pane1.setHgap(10);
  pane1.setPadding(new Insets(10,10,10,250));
  pane1.setConstraints(submitButton,0,0);
  pane1.setConstraints(clearResultButton,1,0);
  pane1.getChildren().addAll(submitButton,clearResultButton);
  mainPane.setBottom(pane1);
  pane3.setPadding(new Insets(10,10,10,10));
  pane3.setVgap(8);
  pane3.setHgap(10);
  searchField = new TextField();
  pane3.setConstraints(searchField, 0, 0);
  searchButton = new Button("search");
  pane3.setConstraints(searchButton, 0, 1);
  pane3.getChildren().addAll(searchField,searchButton);
  mainPane.setLeft(pane3);
  Scene scene = new Scene(mainPane, 600,500);
  scene.getStylesheets().add("gui/style.css");
  primaryStage.setScene(scene);
  primaryStage.show();
}
}
